# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b4422f646f78af6fb75b25f216277e5f989158688ed00a940e957a0bcd40252ea5593b94d951599882bf3d2331a6a583459571209725694c96926f7519c9e56

test:
  secret_key_base: 1c28a02e7d81e2f83d85de5f4fdcc58848544fb79eca61e0762040768580de70e83778199b04e7b85e7a6da6993cd6cabeeac90570e586f9c66f33b04acb1323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
